# Generated by Django 3.2.7 on 2021-09-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_rename_users_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=8716857),
        ),
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.IntegerField(default=8484564),
        ),
        migrations.AddField(
            model_name='user',
            name='email_Id',
            field=models.EmailField(default='user@gmail.com', max_length=254),
        ),
    ]
