# Generated by Django 3.2.7 on 2021-09-19 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_deposit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_Id',
            new_name='email_id',
        ),
    ]
